import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import styled from "styled-components";
// import React, { useState, useEffect, useLayoutEffect, useRef, useCallback, useMemo } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>typescript 홈</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Test>
          dd2
        </Test>
      </main>
    </>
  );
}


const Test = styled.p`
  color: red;
`