import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import styled from "styled-components";
import Card from "@/components/Card";
import { Children } from "react";

import { useRouter } from 'next/router';

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>

        <Card/>
      </main>
      dd
    </>
  );
}

const Header = styled.div`
  padding : 30px 0 0;
  display : flex;
  gap : 30px;
`